Api
miljan-kolosek/ghost-Miljan pull request #13
Opened 2020-11-25 12:11 UTC by miljan-kolosek

2020-11-26 08:23 UTC, tamara-kolosek requested changes

2020-11-26 08:23 UTC, tamara-kolosek commented on app/controllers/api/v1/stories_controller.rb
> +
delete sufficient comments

2020-11-26 08:23 UTC, tamara-kolosek commented on app/controllers/stories_controller.rb
>      else
Why didnt you move needed logic into API controler

2020-11-26 08:23 UTC, tamara-kolosek commented on app/models/api_key.rb
> +    end while self.class.exists?(access_token: access_token)
did you find this somewhere?

2020-11-26 08:28 UTC, miljan-kolosek commented on app/models/api_key.rb
> +    end while self.class.exists?(access_token: access_token)
I found it through the instruction on the ticket.

2020-11-26 08:29 UTC, miljan-kolosek commented on app/controllers/stories_controller.rb
>      else
I followed the tutorial.

2020-11-27 07:52 UTC, tamara-kolosek commented on app/controllers/stories_controller.rb
>      else
Ok but if someone will use the api, will get different data?

2020-11-27 08:06 UTC, miljan-kolosek commented on app/controllers/stories_controller.rb
>      else
Sorry, I don't understand. Can you explain me more about that?

2020-11-27 08:34 UTC, tamara-kolosek requested changes

2020-11-27 08:34 UTC, tamara-kolosek commented on app/controllers/stories_controller.rb
>      else
Just compare your index method in api, and the one in stories controller

2020-11-27 08:36 UTC, miljan-kolosek commented on app/controllers/stories_controller.rb
>      else
@all_stories = Story.all
respond_to do |format|
 format.html
 format.json { render json: @all_stories } 

Is that correct?

2020-11-30 08:29 UTC, tamara-kolosek requested changes

2020-11-30 08:29 UTC, tamara-kolosek commented on app/controllers/stories_controller.rb
> +    @all_stories = Story.all
why this here. How many queries will you make?

2020-11-30 08:46 UTC, miljan-kolosek commented on app/controllers/stories_controller.rb
>      else
What exactly way do you mean,  I need to cover both cases?

2020-11-30 09:07 UTC, tamara-kolosek commented on app/controllers/stories_controller.rb
>      else
I just mean on that, if you are doing this search in this controller, why you ommited it in your api version?

2020-11-30 09:13 UTC, miljan-kolosek commented on app/controllers/stories_controller.rb
>      else
I understood that all stories should be shown in the api version, my mistake. Next step is to change api controller to be same like this controller?

2020-11-30 09:17 UTC, tamara-kolosek approved these changes

2020-11-30 09:17 UTC, tamara-kolosek commented on app/controllers/stories_controller.rb
>      else
Do however you want, this is the exercise anyway, but I do not see the reason why that two will behave different.

2020-11-30 09:20 UTC, miljan-kolosek commented on app/controllers/stories_controller.rb
>      else
I will change to be the same.

2020-11-30 13:03 UTC, merged