[#175716279][#175716280] Added feature and model tests
miljan-kolosek/ghost-Miljan pull request #19
Opened 2020-11-26 15:58 UTC by miljan-kolosek

2020-11-27 08:01 UTC, tamara-kolosek requested changes

2020-11-27 08:01 UTC, tamara-kolosek commented on spec/models/user_spec.rb
> +
Aren't there any method in User model (and other models) to be tested
For example: pdate_admin, compute slug.. and scopes also

2020-11-27 12:56 UTC, tamara-kolosek requested changes

2020-11-27 12:56 UTC, tamara-kolosek commented on spec/models/user_spec.rb
> +
when testing methods, test different cases

2020-11-27 12:58 UTC, tamara-kolosek requested changes

2020-11-27 12:58 UTC, tamara-kolosek commented on spec/models/story_spec.rb
> +
havent you method tag_list ?

2020-11-27 13:13 UTC, miljan-kolosek commented on spec/models/story_spec.rb
> +
Yes, I have.

2020-11-30 14:51 UTC, tamara-kolosek approved these changes

2020-11-30 14:51 UTC, tamara-kolosek commented on spec/models/story_spec.rb
> +        ])
seems like it somehow work. Could you just explain when  tag_list= is beeing called?

2020-11-30 15:34 UTC, miljan-kolosek commented on spec/models/story_spec.rb
> +        ])
Method "tag_list" is called in form when I insert tags into a story, and make tags like array "tag1, tag2". After that, method tag_list=(tags_string) convert all tags into separate object.

2020-12-01 07:50 UTC, miljan-kolosek commented on spec/models/story_spec.rb
> +        ])
Method was called on 30 line of code : ` @story.tag_list = "123, 345"`.

2020-12-01 08:10 UTC, tamara-kolosek approved these changes

2020-12-01 08:10 UTC, tamara-kolosek commented on spec/models/story_spec.rb
> +        ])
OK, I see this is something called, assignment method.

2020-12-01 08:13 UTC, merged