[#175716281] Manage access permissions
miljan-kolosek/ghost-Miljan pull request #20
Opened 2020-11-30 12:58 UTC by miljan-kolosek

2020-11-30 14:42 UTC, tamara-kolosek requested changes

2020-11-30 14:42 UTC, tamara-kolosek commented on app/controllers/stories_controller.rb
> +    @users = User.all.decorate
maybe except admins

2020-11-30 14:42 UTC, tamara-kolosek commented on app/controllers/users_controller.rb
> +    @user.save
isn't the requirement that admin set users permission for separate story.

This way, when user gets auditor role, all the stories will be hidden from him, not just targeted one,  right? and vice versa

2020-12-01 09:35 UTC, miljan-kolosek commented on app/controllers/users_controller.rb
> +    @user.save
The requirement is that admin set users permission to be on the list for access to stories and that is implemented.
When user gets auditor role, all stories will be hidden from him except his stories,and thats the logic from previous tickets.

2020-12-01 09:35 UTC, miljan-kolosek commented on app/controllers/stories_controller.rb
> +    @users = User.all.decorate
Yes, I fix that.

2020-12-02 10:40 UTC, tamara-kolosek approved these changes

2020-12-02 10:55 UTC, merged