Upload image profile
miljan-kolosek/ghost-Miljan pull request #3
Opened 2020-11-17 15:50 UTC by miljan-kolosek

2020-11-17 16:04 UTC, tamara-kolosek requested changes

2020-11-17 16:04 UTC, tamara-kolosek commented on app/views/users/edit.html.erb
> +      <img src="https://www.vhv.rs/dpng/d/256-2569650_men-profile-icon-png-image-free-download-searchpng.png" height="200" weight="200">
since you getting src from url, provide alt for this, or store localy

2020-11-17 16:04 UTC, tamara-kolosek commented on db/migrate/20201117113813_add_profile_image_to_users.rb
> +    add_column :users, :image, :string
why both?

2020-11-17 16:09 UTC, miljan-kolosek commented on db/migrate/20201117113813_add_profile_image_to_users.rb
> +    add_column :users, :image, :string
Because I made mistake with removing column manually. After that I fix the problem with that migation.

2020-11-18 09:16 UTC, tamara-kolosek commented on db/migrate/20201117113813_add_profile_image_to_users.rb
> +    add_column :users, :image, :string
Ok but will it fail for someone run a migrations for a first time? - attempt of removing column that isnt presented.

However, please cleanup the migrations then

2020-11-18 09:46 UTC, tamara-kolosek commented on app/decorators/user_decorator.rb
> +    end
you can use early return for prettier code. its fine, you can decide

2020-11-18 09:46 UTC, tamara-kolosek commented on app/controllers/users_controller.rb
> -	    @user = User.find(params[:id])
correct identation

2020-11-18 10:05 UTC, merged